server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://***********:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ***********
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    文件上传
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

  #    解决SpringBoot版本（太高）和swagger版本不兼容的问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 配置redis
  redis:
    host: ***********
    port: 6379
    password: ***********
    lettuce:
      pool:
        max-active: 8   #最大连接数
        max-idle: 8     #最大空闲连接数
        min-idle: 0     #最小空闲连接数
        max-wait: 100ms #等待连接时间

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #      逻辑删除字段
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto


# 阿里云OSS对象存储
oss:
  #  配置地域节点Endpoint
  endpoint: ***************************
  accessKeyId: ***************************
  accessKeySecret: ***************************
  bucketName: ***************************
